# Generated by Django 5.1.4 on 2024-12-14 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wars', '0004_userprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='warsUser',
        ),
    ]
