# Generated by Django 5.1.4 on 2024-12-14 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wars', '0005_rename_users_warsuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='name',
            new_name='names',
        ),
    ]
