# Generated by Django 5.1.4 on 2024-12-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wars', '0006_rename_name_contactmessage_names'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warsuser',
            old_name='national_id',
            new_name='nationalId',
        ),
        migrations.RenameField(
            model_name='warsuser',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nationality',
            field=models.CharField(choices=[('Rwandan', 'Rwandan'), ('Other', 'Other')], default='Rwandan', max_length=20),
        ),
        migrations.AddField(
            model_name='warsuser',
            name='dob',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='warsuser',
            name='emergencyContact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='warsuser',
            name='gender',
            field=models.CharField(default='Other', max_length=10),
        ),
        migrations.AddField(
            model_name='warsuser',
            name='nationality',
            field=models.CharField(default='Rwandan', max_length=100),
        ),
    ]
