# Generated by Django 5.1.4 on 2024-12-15 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wars', '0008_alter_warsuser_nationalid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('tap_id', models.CharField(max_length=20, unique=True)),
                ('date_added', models.DateTimeField(default=datetime.datetime)),
            ],
        ),
    ]
