# Generated by Django 5.1.4 on 2024-12-15 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wars', '0009_tap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tap',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
