# Generated by Django 5.1.4 on 2024-12-15 18:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wars', '0010_alter_tap_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tap',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
